name: morning

on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '24 0 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  update:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      # Runs a single command using the runners shell
      - name: convert to Japanese
        run: |
          sed 's/World/世界/' hello.c > hello.c.jp 
          mv hello.c.jp hello.c

      - name: compile
        run: gcc hello.c
      
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 🌱 improvements 🌱
          commit_user_name: Ann Kilzer
          commit_user_email: ann-kilzer@users.noreply.github.com
          commit_author: Ann Kilzer <ann-kilzer@users.noreply.github.com>
